### ISSUE TITLE
Support for additional summary formats

### ISSUE THREAD

**Issue by laura-nao** [fluendo/fluster#104]
I would like to add support for generating the results summary in a different format, in addition to markdown. The main motivation is to facilitate parsing the results when the conformance tests are run in a CI, as well as representing the results using standard formats for test reporting (such as JUnit or TAP).

A JUnit XML report for example might look like this:

```
<?xml version='1.0' encoding='utf-8'?>
<testsuites>
    <testsuite name="VP8-TEST-VECTORS" tests="61" errors="0" failures="17" skipped="0" time="0.46">
        <properties>
            <property name="decoder" value="FFmpeg-VP8" />
        </properties>
...
        <testcase name="vp80-02-inter-1418" />
        <testcase name="vp80-02-inter-1424">
            <failure message="self.assertEqual(\nAssertionError: \'4816cb607488b930ceadeb2cdb034c49\' != \'927e475e4eba7e605a504ea0c97742d9\'\n- 4816cb607488b930ceadeb2cdb034c49\n+ 927e475e4eba7e605a504ea0c97742d9\n : vp80-02-inter-1424\n'" />
        </testcase>
...
    </testsuite>
</testsuites>
```

Generating the summary in JUnit format would be pretty straightforward using an external library. As fluster currently does not have any dependency, I wanted to ask first whether using external libraries would be an option.

I'd like to know your thoughts on this.

Thanks!

**Comment by rgonzalezfluendo** [comment]
We prefer to avoid external dependencies for the default operation. A  Fluster requirement is to be able to run only with Python installed.

But we don't want to close the door to new features and contributions. Fluster is a tool for the community. Therefore, we will accept any contributions if the dependency is only needed when the new functionality is enabled. For instance:

Raw python
```$ ./fluster.py run --format md
...
|Test|FFmpeg-H.264|
|TOTAL|1/1|
|TOTAL TIME|0.132s|

$ ./fluster.py run -f md --format junit
fluster.py: error: module "XXX" required to use Junit format. Please install with pip install XXX (or similar)
```

Please let us know your  thoughts about this rule. If there are reasons to disregard it, we can always reach an agreement. But please let us know.

PS: We prefer JUnit, but all contributions are welcome.

**Comment by laura-nao** [comment]
Sounds more than reasonable, I'll make sure the dependency is required only if the JUnit format is used (I'm currently trying out [junitparser](https://github.com/weiwei/junitparser)). I'll submit a PR to add JUnit support soon.

Thanks for the feedback!

**Comment by laura-nao** [comment]
PR: https://github.com/fluendo/fluster/pull/107

Please let me know if you have any remarks on the proposed solution. Thanks!
