### ISSUE TITLE
Running `fluster download invalid` silently exists

### ISSUE THREAD

**Issue by evelikov** [fluendo/fluster#63]
Currently, if we have a typo/invalid test suite name, fluster will silently exit.
While returning 0, indicating that everything was successful :confused: 

Can we please get some indicative error messages in, plus ideally a "all" target which downloads?

Thanks

**Comment by rgonzalezfluendo** [comment]
Please could you confirm if the `silently exit` was fixed in the commit https://github.com/fluendo/fluster/commit/1a0912eb1cbf81a67404c363d2a9773cd00e6d1f

My current output of an invalid test suite name is:
```
./fluster.py run -tv JCT-VC-HEVC_V1 -ts  AMP_B_Samsung_7_TYPO
No test suite found matching ['amp_b_samsung_7_typo']```

Seem there is a bug downloading all test suits. We are working in a PR. Thanks to report.

**Comment by pamarcos** [comment]
Fixed in https://github.com/fluendo/fluster/pull/65
@evelikov could you try again and reopen if it didn't fix your use case?

**Comment by evelikov** [comment]
With the linked MR we get an error now \o/

Neither `fluster download all` or `fluster download --all` seems to be a thing. Guess it's something for the future.

**Comment by pamarcos** [comment]
It's `fluster download` without specifying any other param so that no filter is aplied. The same can be applied to any other fluster parameter as `run`. When no extra parameters (-d for decoders, -ts for test suites or -tv for test vectors) is given, all that can be found are used.
